- name: Install PyMySQL
  pip:
    name: pymysql
    state: present

- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20220616100836058700000001.ctzmlixwicc8.us-east-1.rds.amazonaws.com"
    login_user: "moses"
    login_password: "moses12345"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - {
        regexp: "^mysql.tooling.svc.cluster.local",
        line: "terraform-20220616100836058700000001.ctzmlixwicc8.us-east-1.rds.amazonaws.com",
      }
    - { regexp: "^admin", line: "moses" }
    - { regexp: "^tooling", line: "toolingdb" }
    - { regexp: "^admin", line: "moses12345" }
